
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aadi
 */
public class LoginForm extends javax.swing.JFrame {
AdminMenuForm m ;
Admin admin = Admin.getInstance();


public boolean LoginShow()
{ 
    boolean flagA = false;
    String username = textField1.getText();
        int size = username.length();
       if( !(username.charAt(size-1)=='k' && username.charAt(size-2)=='p' && username.charAt(size-3)=='.'&&
          username.charAt(size-4)=='u'&&username.charAt(size-5)=='d'&&username.charAt(size-6)=='e'
          && username.charAt(size-7) == '.' && username.charAt(size-8) == 't'&& username.charAt(size-9) == 'e'
          && username.charAt(size-10) == 'u'&& username.charAt(size-11) == '.'&& username.charAt(size-12) == 'n'
           && username.charAt(size-13) == 'i' && username.charAt(size-14) == 'm'&& username.charAt(size-15) == 'd' && username.charAt(size-16) == 'a' ))
 
       {
           return flagA;
       }
           for(int i=0;i<size-17;i++)
       {
           if(username.charAt(i)>='a'&& username.charAt(i)<='z' || username.charAt(i)>='A'&&username.charAt(i)<='Z'
              || username.charAt(i)>='0'&&username.charAt(i)<='9')
           {
             flagA = true;  
           }
           
       }
          String pass =PasswordField.getText();
          int length= pass.length();
          for(int j=0;j<length;j++)
          {
              if( !(pass.charAt(j)>='A'&& pass.charAt(j)<='Z'||pass.charAt(j)>='a'&& pass.charAt(j)<='z' 
                || pass.charAt(j)>='0'&& pass.charAt(j)<='9' || pass.charAt(j)=='"' || pass.charAt(j)=='@'
                 || pass.charAt(j)=='#'|| pass.charAt(j)=='%' || pass.charAt(j)=='$' || pass.charAt(j)=='!') )
              {
                 flagA = false;
                 return flagA;
              }
          }
          
    return flagA;
}
/**
 * Method to Teacher admin
 */
    public boolean Addteacher(String user,String Pass)
       {
           boolean  flag = false;
           if( !(admin.getTeachList().isEmpty()) )
           {
              for(int i=0;i<admin.getTeachList().size();i++)
           {
               if( (user.equals(admin.getTeachList().get(i).getEmail())) && Pass.equals(admin.getTeachList().get(i).getPassword()) )
               {
                   flag = true;
               }
           } 
           }
           else
           {
               
           }
           
           
           return flag;
       }


    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        PassHint.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginLabl = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        HelpBtn = new java.awt.Label();
        label4 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        label1 = new java.awt.Label();
        EmailLBL = new java.awt.Label();
        EmailLBL1 = new java.awt.Label();
        PasswordField = new javax.swing.JPasswordField();
        showPasCheck = new javax.swing.JCheckBox();
        button1 = new java.awt.Button();
        label3 = new java.awt.Label();
        PassHint = new javax.swing.JLabel();

        LoginLabl.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        LoginLabl.setText("Login");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginPanel.setBackground(new java.awt.Color(0, 102, 153));

        HelpBtn.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        HelpBtn.setForeground(new java.awt.Color(255, 255, 255));
        HelpBtn.setText("Help");
        HelpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpBtnMouseClicked(evt);
            }
        });

        label4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Rubrics Based Evaluation");

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(HelpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(HelpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        textField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textField1MouseEntered(evt);
            }
        });
        textField1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                textField1MouseDragged(evt);
            }
        });
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        textField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textField1KeyTyped(evt);
            }
        });

        label1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        label1.setText("LOGIN");

        EmailLBL.setText("Password");

        EmailLBL1.setText("Email");

        PasswordField.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PasswordFieldMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PasswordFieldMouseMoved(evt);
            }
        });
        PasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PasswordFieldMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordFieldMousePressed(evt);
            }
        });
        PasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordFieldKeyPressed(evt);
            }
        });

        showPasCheck.setText("ShowPassword");
        showPasCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasCheckActionPerformed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(0, 102, 153));
        button1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Login");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        label3.setText("Reset Password");

        PassHint.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        PassHint.setForeground(new java.awt.Color(255, 51, 51));
        PassHint.setText(" Must have 1 Digit & special char(@,!,*.. )");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(EmailLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(EmailLBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PasswordField)
                            .addComponent(button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                            .addComponent(showPasCheck)
                            .addComponent(PassHint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(EmailLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailLBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PassHint, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(showPasCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
        
       
       
    }//GEN-LAST:event_textField1ActionPerformed

    private void textField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textField1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1MouseEntered

    private void textField1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textField1MouseDragged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_textField1MouseDragged

    private void textField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField1KeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textField1KeyTyped

    private void showPasCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasCheckActionPerformed
        // TODO add your handling code here:
        if(showPasCheck.isSelected())
        
        {
            PasswordField.setEchoChar((char)0);
        }
        else
        {
            PasswordField.setEchoChar(('*'));
        }
    }//GEN-LAST:event_showPasCheckActionPerformed

    private void HelpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpBtnMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"If Teacher then "+"\n"
         +"xxxxx.teacher.uet.edu.pk"+"\n"+"If Admin then"+"\n"+"aaaaaa.admin.uet.edu.pk");
    }//GEN-LAST:event_HelpBtnMouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
            String us =textField1.getText();
            String pas = PasswordField.getText();
        boolean flag =LoginShow();
        boolean flag1 = Addteacher(us,pas);
        if(flag == true)
        {
            
            admin.setUserName(us);
            admin.setPassword(pas);
            //JOptionPane.showMessageDialog(null,admin.getUserName()+"\n" + admin.getPassWord());
            m= new AdminMenuForm();
            m.setVisible(true);
            this.setVisible(false);
        }
        else if(flag1==true)
        {
            TeacherForm tform = new TeacherForm(us,pas);
            tform.setVisible(true);
            this.setVisible(false);
        }
        else if(flag1==false)
        {
            JOptionPane.showMessageDialog(null,"Teacher's List is Empty ....");
        }
       
    }//GEN-LAST:event_button1ActionPerformed

    private void PasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PasswordFieldKeyPressed

    private void PasswordFieldMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldMouseDragged
        // TODO add your handling code here:
      
    }//GEN-LAST:event_PasswordFieldMouseDragged

    private void PasswordFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_PasswordFieldMouseEntered

    private void PasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldMousePressed
        // TODO add your handling code here:
        PassHint.setVisible(true);
    }//GEN-LAST:event_PasswordFieldMousePressed

    private void PasswordFieldMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldMouseMoved
        // TODO add your handling code here:
        PassHint.setVisible(false);
    }//GEN-LAST:event_PasswordFieldMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label EmailLBL;
    private java.awt.Label EmailLBL1;
    private java.awt.Label HelpBtn;
    private javax.swing.JLabel LoginLabl;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel PassHint;
    private javax.swing.JPasswordField PasswordField;
    private java.awt.Button button1;
    private java.awt.Label label1;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JCheckBox showPasCheck;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
